---
 - name: Comparison Operators for Ansible
   hosts: localhost
   gather_facts: false
   vars:
     num1: 10
     num2: 20
   tasks:
   -  debug:
         msg:
          - "The value of num1 and num2 is: {{ num1 }} and {{ num2 }}"
          - "num1 is equal to num2: {{ num1 == num2}}"
          - "num1 is not equal to num2: {{ num1 != num2}}"
          - "num1 is greater than num2: {{ num1 > num2}}"
          - "num1 is less than num2: {{ num1 < num2}}"
          - "num1 is greater than equal to num2: {{ num1 >= num2}}"
          - "num1 is less than equal to num2: {{ num1 <= num2}}"
